services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: phishing-backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: phishing-frontend
    depends_on:
      - backend
    restart: unless-stopped
